In [1]:
import os, sys
import numpy as np
module_path = os.path.abspath(os.path.join('..'))
sys.path.append(os.path.join(module_path, "KAN_variants"))
from ChebyKANLayer import ChebyKAN

module_path = os.path.abspath(os.path.join('..'))
sys.path.append(os.path.join(module_path, "code"))
from myKANODE import KANODE

In [2]:
def pred_prey_deriv(X, t, alpha, beta, delta, gamma):
    x=X[0]
    y=X[1]
    dxdt = alpha*x-beta*x*y
    dydt = delta*x*y-gamma*y
    dXdt=[dxdt, dydt]
    return dXdt

# alpha, beta, delta, gamma
params = [1.5, 1, 2, 1]
X0 = [0.1, 1.5]

In [10]:
def standardiseData(data, lowerBound = 0.1, upperBound = 0.9):
    normData = np.zeros(data.shape)
    for colIndex, column in enumerate(np.transpose(data)):
        normData[:, colIndex] = (upperBound - lowerBound) * ((column - np.min(column)) / (np.max(column) - np.min(column))) + lowerBound
    return normData


def deStandardiseData(data, dataMax, dataMin, lowerBound = 0.1, upperBound = 0.9):
    data = np.zeros(data.shape)
    for colIndex, column in enumerate(np.transpose(data)):
        data[:, colIndex] = ((column - lowerBound) / upperBound) * (dataMax - dataMin) + dataMin
    return data


In [11]:
test = np.array([[0.1, 0.5, 0.9], [0, 0.4, 1]])
test

array([[0.1, 0.5, 0.9],
       [0. , 0.4, 1. ]])

In [13]:
standardiseData(np.transpose(test))

array([[0.1 , 0.1 ],
       [0.5 , 0.42],
       [0.9 , 0.9 ]])

In [4]:
model = ChebyKAN([2, 10, 2], 4)
kanODE = KANODE(model, pred_prey_deriv, X0, params, 20, 7.5, 100)

In [14]:
kanODE.baseSolution

tensor([[0.1000, 1.5000],
        [0.1000, 1.4880],
        [0.1000, 1.4762],
        ...,
        [0.9707, 0.5639],
        [0.9799, 0.5693],
        [0.9890, 0.5748]], requires_grad=True)

In [25]:
test = standardiseData(kanODE.baseSolution.detach().numpy())
test

array([[0.1       , 0.36713022],
       [0.1000036 , 0.36415073],
       [0.10001437, 0.36119509],
       ...,
       [0.62368065, 0.13389209],
       [0.62915832, 0.13523474],
       [0.63465494, 0.13661641]])

In [23]:
np.max(test)

0.9000000357627869